export const RAJASTHAN_CITIES = [
  {
    id: 'jaipur',
    name: 'Jaipur',
    tagline: 'Pink City Central Cloud Kitchens (36+ Hubs)',
    hubsCount: '36+ Hubs',
    deliveryTime: '20-25 mins',
    rating: '4.95 ★',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80',
    specialties: ['Royal Dal Baati Churma in Pure Gir Ghee', 'Ker Sangri Missi Roti', 'Govind Gatte Thali', 'Desi Ghee Ghevar', 'Kulhad Pizza & Momos'],
    localities: [
      'Malviya Nagar (Hub 1 - GT & World Trade Park)',
      'Mansarovar (Hub 2 - VT Road & City Park)',
      'Vaishali Nagar (Hub 3 - Queens Road & Amrapali)',
      'C-Scheme & Ashok Nagar (Hub 4)',
      'Raja Park & Jawahar Nagar (Hub 5)',
      'Jagatpura & Model Town',
      'Sitapura Industrial & Educational Hub',
      'Civil Lines (VIP Zone & Raj Bhavan)',
      'Tilak Nagar & Sethi Colony',
      'Tonk Road & Durgapura Flyover',
      'Gopalpura Bypass & Triveni Nagar',
      'Sodala & Ram Nagar',
      'Shyam Nagar & Janpath',
      'Nirman Nagar & DCM',
      'Vidyadhar Nagar (Sector 1-9)',
      'Bani Park & Kanti Nagar',
      'Shastri Nagar & Subhash Nagar',
      'Muralipura & Sikar Road',
      'Jhotwara & Kalwar Road',
      'Pratap Nagar (Sector 1-28)',
      'Sanganer Town & Airport Road',
      'MI Road & Panch Batti',
      'Johari Bazar & Bapu Bazar (Walled City)',
      'Amer Road & Subhash Chowk',
      'Ajmer Road (Heerapura & 200 Feet Bypass)',
      'Mahindra World City (SEZ Area)',
      'VKI Area (Vishwakarma Industrial Area)',
      'Mahesh Nagar & 80 Feet Road',
      'Lalkothi & Jyoti Nagar',
      'Bais Godam & 22 Godam Circle',
      'Gandhinagar & Bajaj Nagar',
      'Khatipura & Sirsi Road',
      'Chitrakoot & Gandhi Path',
      'Brahmpuri & Jal Mahal Outskirts',
      'Goner Road & Luniyawas',
      'Bhakrota & Toll Plaza Corridor'
    ]
  },
  {
    id: 'ajmer',
    name: 'Ajmer',
    tagline: 'Ana Sagar & Heritage Kitchen Hubs (28+ Hubs)',
    hubsCount: '28+ Hubs',
    deliveryTime: '20-25 mins',
    rating: '4.92 ★',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
    specialties: ['Desi Ghee Kadhi Khichdi', 'Sohan Halwa Thali', 'Laal Maas (Non-Veg)', 'Satvik Jain Thali', 'Tandoori Momos & Fast Bites'],
    localities: [
      'Panchsheel Nagar (Hub 1 - Sector A-G)',
      'Vaishali Nagar (Hub 2 - Sagar Vihar)',
      'Civil Lines & Collectorate Area',
      'Ana Sagar Circular Road & Chowpatty',
      'Adarsh Nagar (Parbatpura Bypass)',
      'Kundan Nagar & Alwar Gate',
      'Topdara & Railway Station Road',
      'Kaiser Ganj & Martindale Bridge',
      'Naya Bazar & Delhi Gate',
      'Dargah Bazaar & Andar Kot',
      'JLN Hospital & Medical College Campus',
      'Foy Sagar Road & Haribhau Nagar',
      'Shastri Nagar & Regional College (RIE)',
      'Makarwali Road (Mittal Hospital)',
      'Madar & Madar Railway Junction',
      'Beawar Road & Pal Beechla',
      'Ghooghra Ghati & MDS University Campus',
      'Kotra & Chaurasiyawas Road',
      'Mayo College & Alwar Gate Outskirts',
      'Ramganj & Subhash Nagar',
      'Bajrang Garh & Nagphani Area',
      'Hathi Bhata & Station Road',
      'Ganj & Subhash Udhyan Road',
      'Prithviraj Nagar & BK Kaul Nagar',
      'Chanderi & Tabiji Industrial Area',
      'Someshwar Nagar & Gulab Bari',
      'Boraj & Pushkar Bypass T-Point',
      'Police Lines & Golf Course Area'
    ]
  },
  {
    id: 'kishangarh',
    name: 'Kishangarh',
    tagline: 'Marble City Express Tiffins (16+ Hubs)',
    hubsCount: '16+ Hubs',
    deliveryTime: '20-30 mins',
    rating: '4.90 ★',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    specialties: ['Marble City Deluxe Thali', 'Dal Dhokli', 'Bilona Ghee Phulkas', 'Panchmel Dal', 'Cheesy Pasta & Street Food'],
    localities: [
      'Madanganj (Central Hub 1)',
      'Marble Industrial Area (Zone 1-4)',
      'RK Marble Circle & Mega Highway',
      'City Center & Old Bus Stand',
      'Old City Kishangarh & Mokham Vilas',
      'Bandarsindri (Central University of Rajasthan - CURAJ)',
      'Harmara Road & Krishi Mandi',
      'Ajmer Road Bypass & Toll Hub',
      'Gudda Road & Gandhi Nagar',
      'Silora Industrial Area & RIICO',
      'Koda Road & Ratan Colony',
      'Tehsil Road & Court Complex',
      'Airport Road Kishangarh (KQH)',
      'Tirupati Nagar & Housing Board',
      'Suraj Pole & Phool Mahal Palace Outskirts',
      'Salemabad & Nimbark Peeth Area'
    ]
  }
];
